# A Blueprint for the ShiftBot application, with corrected structure
# for disks and addons.

# Top-level 'disks' definition
disks:
  - name: shiftbot-data # Define the disk once here
    mountPath: /var/data
    sizeGB: 1

# Top-level 'addons' definition
addons:
  - name: shiftbot-redis # Define the redis addon once here
    plan: free
    region: virginia

# Services that will use the above resources
services:
  - type: web
    name: shiftbot-api
    runtime: python
    plan: free
    region: virginia
    buildCommand: |
      pip install -r requirements.txt
      playwright install --with-deps chromium
    startCommand: "gunicorn -w 4 app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.2
      - key: FLASK_ENV
        value: production
      - key: REDIS_URL
        fromService:
          type: redis
          name: shiftbot-redis # Reference the addon
          property: connectionString
      - key: SQLALCHEMY_DATABASE_URI
        value: sqlite:////var/data/site.db # Path uses the mounted disk
    # This section now just references the disk defined at the top level
    disk:
      name: shiftbot-data
      mountPath: /var/data
      
  - type: worker
    name: shiftbot-celery
    runtime: python
    plan: free
    region: virginia
    buildCommand: |
      pip install -r requirements.txt
      playwright install --with-deps chromium
    startCommand: "celery -A celery_init.celery_app worker --loglevel=info --pool=solo"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.2
      - key: REDIS_URL
        fromService:
          type: redis
          name: shiftbot-redis # Reference the addon
          property: connectionString
      - key: SQLALCHEMY_DATABASE_URI
        value: sqlite:////var/data/site.db # Path uses the mounted disk
      # Secrets to be added in the UI
      - key: FLASK_SECRET_KEY
        sync: false
      - key: MSAL_CLIENT_ID
        sync: false
      - key: MSAL_AUTHORITY
        sync: false
      - key: BOT_SENDER_EMAIL
        sync: false
    # This section also references the same disk
    disk:
      name: shiftbot-data
      mountPath: /var/data