services:
  - type: web
    name: shiftbot-api
    runtime: python
    plan: free
    region: virginia
    buildCommand: |
      pip install -r requirements.txt
      playwright install --with-deps chromium
    startCommand: "gunicorn -w 4 app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.2
      - key: FLASK_ENV
        value: production
      - key: REDIS_URL
        fromService:
          type: redis
          name: shiftbot-redis
          property: connectionString

  - type: worker
    name: shiftbot-celery
    runtime: python
    plan: free
    region: virginia
    buildCommand: |
      pip install -r requirements.txt
      playwright install --with-deps chromium
    startCommand: "celery -A tasks worker --loglevel=info --pool=solo"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.2
      - key: REDIS_URL
        fromService:
          type: redis
          name: shiftbot-redis
          property: connectionString
      - key: FLASK_SECRET_KEY
        sync: false
      - key: SQLALCHEMY_DATABASE_URI
        sync: false
      - key: MSAL_CLIENT_ID
        sync: false
      - key: MSAL_AUTHORITY
        sync: false
      - key: BOT_SENDER_EMAIL
        sync: false

addons:
  - name: shiftbot-redis
    plan: free
    region: virginia