# render.yaml  —  Infrastructure-as-code for Render.com
#
# Put this file next to requirements.txt.
# Render autoscans the repo; each “service” below becomes a button-free deployment.

services:
  # ────────────────────────────────────────────────────────────────
  - type: web                     # Public HTTP entry-point
    name: shiftbot-api            # Whatever name you like (shows in Render UI)
    env: python
    region: oregon                # Pick the region closest to most users
    plan: free                    # Forever-free web instance (750 hrs / month)
    buildCommand:  pip install -r requirements.txt
	python -m playwright install --with-deps
    startCommand: python app.py
    numInstances: 1
    autoDeploy: true              # re-deploy when you push to GitHub main
    # Optional: environment variables that only the web service needs
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SQLALCHEMY_DATABASE_URI
        sync: false     # add the actual URI in the Render dashboard UI

  # ────────────────────────────────────────────────────────────────
  - type: worker                  # Background Celery worker
    name: shiftbot-celery
    env: python
    region: oregon
    plan: free                    # Shares the free-tier hour pool
    buildCommand:  pip install -r requirements.txt
    python -m playwright install --with-deps
    startCommand: celery -A celery_init.celery_app worker --loglevel=info --pool=solo
    numInstances: 1
    autoDeploy: true
    envVars:                      # Same vars as web + anything worker-only
      - fromService:
          type: redis
          name: shiftbot-redis    # will inject REDIS_URL automatically

  # ────────────────────────────────────────────────────────────────
  # Free 30 MB volatile Redis used as Celery broker & cache
  - type: redis
    name: shiftbot-redis
    ipAllowList: []               # empty = accessible only from your services
    plan: free

