services:
  # 1. The PostgreSQL Database
  - type: pserv
    name: shiftbot-db
    plan: free
    region: virginia
    databaseName: shiftbot_db 
    user: shiftbot_user

  # 2. The Redis Add-on
  - type: redis
    name: shiftbot-redis
    plan: free
    region: virginia
    # This IP allow list allows all your other Render services to connect
    ipAllowList:
      - source: 0.0.0.0/0 

  # 3. The Web Service (Flask API)
  - type: web
    name: shiftbot-api
    runtime: python
    plan: free
    region: virginia
    buildCommand: |
      pip install -r requirements.txt
      playwright install --with-deps chromium
    startCommand: "gunicorn -w 4 app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.2
      - key: FLASK_ENV
        value: production
      - key: REDIS_URL
        fromService:
          type: redis
          name: shiftbot-redis
          property: connectionString
      - key: SQLALCHEMY_DATABASE_URI
        fromService:
          type: pserv
          name: shiftbot-db
          property: connectionString
      # Secrets to be added in the UI
      - key: FLASK_SECRET_KEY
        sync: false
      - key: MSAL_CLIENT_ID
        sync: false
      - key: MSAL_AUTHORITY
        sync: false
      - key: BOT_SENDER_EMAIL
        sync: false

  # 4. The Background Worker (Celery)
  - type: worker
    name: shiftbot-celery
    runtime: python
    plan: free
    region: virginia
    buildCommand: |
      pip install -r requirements.txt
      playwright install --with-deps chromium
    startCommand: "celery -A celery_init.celery_app worker --loglevel=info --pool=solo"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.2
      - key: REDIS_URL
        fromService:
          type: redis
          name: shiftbot-redis
          property: connectionString
      - key: SQLALCHEMY_DATABASE_URI
        fromService:
          type: pserv
          name: shiftbot-db
          property: connectionString
      # Secrets to be added in the UI
      - key: FLASK_SECRET_KEY
        sync: false
      - key: MSAL_CLIENT_ID
        sync: false
      - key: MSAL_AUTHORITY
        sync: false
      - key: BOT_SENDER_EMAIL
        sync: false