# ────────────────────────────────────────────────────────────────
#  render.yaml   – Infrastructure-as-code for Render.com
# ────────────────────────────────────────────────────────────────
# 1. Commit this file to the *root* of your repo.
# 2. Push to GitHub.  Render will create / update all services.
# 3. Adjust env-var values (e.g., secrets) in the Render dashboard
#    after the first deploy.
# ----------------------------------------------------------------

services:
  # ── Flask / Gunicorn web service ──────────────────────────────
  - type: web
    name: shiftbot-api
    env: python
    plan: free                    # you can upgrade later
    region: oregon                # pick the same region for all services

    buildCommand: |
      pip install -r requirements.txt
      # Playwright needs its browsers installed at build-time
      python -m playwright install --with-deps

    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT

    autoDeploy: true              # redeploys on every git push

    envVars:
      - key: FLASK_ENV            # enables Flask debug logging
        value: production
      - key: REDIS_URL            # injected from the Redis add-on below
        fromService: shiftbot-redis:url
      # -- add your own secrets here (MSAL client id, DB URI, etc.) --
      # - key: SQLALCHEMY_DATABASE_URI
      #   value: postgres://user:pass@host:5432/dbname

  # ── Celery worker service ─────────────────────────────────────
  - type: worker
    name: shiftbot-celery
    env: python
    plan: free
    region: oregon

    buildCommand: |
      pip install -r requirements.txt
      python -m playwright install --with-deps

    startCommand: celery -A celery_init.celery_app worker --loglevel=info --pool=solo

    envVars:
      - key: REDIS_URL
        fromService: shiftbot-redis:url
      # duplicate any other variables your tasks need
      # - key: SQLALCHEMY_DATABASE_URI
      #   value: postgres://user:pass@host:5432/dbname

# ── Managed Redis instance (free tier) ──────────────────────────
databases:
  - name: shiftbot-redis
    ipAllowList: []               # leave empty = open to all Render services
    plan: free-redis
