# render.yaml  ── defines ALL Render resources
services:
  # ──────────────────────────────────────────────────────────────
  - type: web
    name: shiftbot-api                # public HTTP endpoint
    runtime: python
    plan: free
    region: virginia                   # or virginia, frankfurt, etc.

    buildCommand: |
      pip install -r requirements.txt
      playwright install --with-deps   # Playwright headless deps

    startCommand: |
      gunicorn -k gevent -w 1 -b 0.0.0.0:$PORT app:app

    envVars:
      - key: FLASK_ENV
        value: production
      - key: REDIS_URL                 # Render injects this automatically
        fromService:
          name: shiftbot-redis
          type: redis
          property: connectionString

  # ──────────────────────────────────────────────────────────────
  - type: worker
    name: shiftbot-celery             # background jobs
    runtime: python
    plan: free
    region: virginia

    buildCommand: |
      pip install -r requirements.txt
      playwright install --with-deps

    startCommand: |
      celery -A celery_init.celery_app worker --loglevel=info --pool=solo

    envVars:
      - key: REDIS_URL
        fromService:
          name: shiftbot-redis
          type: redis
          property: connectionString

databases:
  # ──────────────────────────────────────────────────────────────
  - name: shiftbot-redis
    type: redis
    plan: free
    region: virginia
