# A Blueprint for the ShiftBot application
# Defines Redis, Disk, Web Service, and Worker all as services.

services:
  # 1. The Redis Add-on
  - type: redis
    name: shiftbot-redis
    plan: free
    region: virginia
    
  # 2. The Web Service (Flask API)
  - type: web
    name: shiftbot-api
    runtime: python
    plan: free
    region: virginia
    # This section now references the disk defined below
    disk:
      name: shiftbot-data
      mountPath: /var/data
      sizeGB: 1
    buildCommand: |
      pip install -r requirements.txt
      playwright install --with-deps chromium
    startCommand: "gunicorn -w 4 app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.2
      - key: FLASK_ENV
        value: production
      - key: REDIS_URL
        fromService:
          type: redis
          name: shiftbot-redis # Reference the redis service
          property: connectionString
      - key: SQLALCHEMY_DATABASE_URI
        value: sqlite:////var/data/site.db # Path uses the mounted disk
        
  # 3. The Background Worker (Celery)
  - type: worker
    name: shiftbot-celery
    runtime: python
    plan: free
    region: virginia
    # This section also references the same disk
    disk:
      name: shiftbot-data
      mountPath: /var/data
      sizeGB: 1
    buildCommand: |
      pip install -r requirements.txt
      playwright install --with-deps chromium
    startCommand: "celery -A celery_init.celery_app worker --loglevel=info --pool=solo"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.2
      - key: REDIS_URL
        fromService:
          type: redis
          name: shiftbot-redis # Reference the redis service
          property: connectionString
      - key: SQLALCHEMY_DATABASE_URI
        value: sqlite:////var/data/site.db # Path uses the mounted disk
      # Secrets to be added in the UI
      - key: FLASK_SECRET_KEY
        sync: false
      - key: MSAL_CLIENT_ID
        sync: false
      - key: MSAL_AUTHORITY
        sync: false
      - key: BOT_SENDER_EMAIL
        sync: false