services:
  - type: web
    name: shiftbot-api
    runtime: python
    plan: free
    region: virginia
    buildCommand: |
      pip install -r requirements.txt
      playwright install --with-deps chromium
    startCommand: "gunicorn -w 4 app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.2
      - key: FLASK_ENV
        value: production
      - key: REDIS_URL
        fromService:
          type: redis
          name: shiftbot-redis
          property: connectionString
      - key: SQLALCHEMY_DATABASE_URI # This now points to the persistent disk
        value: sqlite:////var/data/site.db
    # This section tells Render to attach the disk we define below
    disks:
      - name: shiftbot-data
        mountPath: /var/data
        sizeGB: 1

  - type: worker
    name: shiftbot-celery
    runtime: python
    plan: free
    region: virginia
    buildCommand: |
      pip install -r requirements.txt
      playwright install --with-deps chromium
    # More specific start command to avoid any ambiguity
    startCommand: "celery -A celery_init.celery_app worker --loglevel=info --pool=solo"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.2
      - key: REDIS_URL
        fromService:
          type: redis
          name: shiftbot-redis
          property: connectionString
      - key: SQLALCHEMY_DATABASE_URI # The worker also needs to know where the DB is
        value: sqlite:////var/data/site.db
      # Add your secrets here when creating the Blueprint in the UI
      - key: FLASK_SECRET_KEY
        sync: false
      - key: MSAL_CLIENT_ID
        sync: false
      - key: MSAL_AUTHORITY
        sync: false
      - key: BOT_SENDER_EMAIL
        sync: false
    # The worker also needs access to the same disk
    disks:
      - name: shiftbot-data
        mountPath: /var/data
        sizeGB: 1

addons:
  - name: shiftbot-redis
    plan: free
    region: virginia